name: Sync Fork

on:
  schedule:
    - cron: '0 13 */7 * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: uses: actions/checkout@v4
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: j-hc
          base: main
          head: main
        continue-on-error: true
      - uses: gautamkrishnar/keepalive-workflow@1.1.0
